### ISSUE TITLE
The Word Stopped

### ISSUE THREAD

**Issue by elvizlai** [pingcap/docs#18] opened 2016-08-07 00:02 UTC
I followed `https://github.com/pingcap/docs/blob/master/op-guide/docker.md` to start all required services, and it succeed.

But when I tried command:

```
docker stop pd5
docker stop pd4
docker start pd4
docker start pd5
```

All services are DOWN.（pd, tikv and tidb）

And It(pd4/pd5) can not started again.

logs `2016/08/06 23:52:36 main.go:45: [error] create pd server err etcdserver: Peer URLs already exists`

It seems that when pd4/pd5 down, It not de-register.

Any helpful log need I provided?
Am I missed something?

**Comment by siddontang** [comment] 2016-08-07 06:10
@overvenus 
Seems we don't handle restarting the pd with join argument.

**Comment by overvenus** [comment] 2016-08-08 03:36
Hi, this error seems caused by join flag.

Now it has been tweaked a little, pingcap/pd#249 should fix this problem, so please use initial-cluster flag for now. Sorry about that.

**Comment by c4pt0r** [comment] 2016-09-21 03:05
@overvenus  any updates?
Seems that we don't support join now?

**Comment by overvenus** [comment] 2016-09-21 06:37
We do support join, but it is a unstable feature, I recommend starting a cluster that contains at least three nodes first, then joining more nodes.

**Comment by overvenus** [comment] 2018-07-23 05:33
We have enhanced the join feature since my last reply, it's stable now. 
I'm closing this since the the issue is no longer active. Please feel free to comment and reopen if you feel the issue has not been resolved.

**Closed by overvenus** 2018-07-23 05:33 UTC
